### PR TITLE
Guess lat/lon columns for viewer when appropriate

### LINKED ISSUE #63: Auto-guess RA and Dec in glue-wwt
pyWWT has some heuristics for guessing ra/dec/lat/lon columns for data layers. It might be nice to use those in glue-wwt instead of just using the first and second columns.

### PR DESCRIPTION
**Pull request by Carifio24**
I saw #63 and thought that was an interesting idea, so this PR uses the relevant pywwt to resolve #63 by guessing lat/lon columns when appropriate. To me, "when appropriate" means when adding the first data layer to the viewer - if there was already a layer in the viewer, the choice might clash with what's already selected (whether that's from the automatic selection or what the user has selected), and unexpectedly changing the viewer state from what's already there is obviously not ideal.

### CODE REVIEW

**Comment by Carifio24** [comment]
Rebased to resolve merge conflicts.

**Review by astrofrog — CHANGES_REQUESTED** [review]
Looks good to me but would be good to add a test

**Comment by Carifio24** [comment]
@astrofrog I've added a couple of tests for this behavior

**Review by astrofrog — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
