### PR TITLE
Add Python 3.11 CI env

### PR DESCRIPTION
**Pull request by dhomeier**
## Description
For good measure testing this with 3.11.0 as well.

### CODE REVIEW

**Comment by dhomeier** [comment]
Upstream action on `reproject` and `pywwt` required; reproject might just need re-cythonising, no idea about pywwt.

**Comment by astrofrog** [comment]
reproject is a WIP

**Comment by dhomeier** [comment]
Yes; installing git+https://github.com/astropy/reproject.git works now.

**Comment by dhomeier** [comment]
pywwt and reproject updates have been released, so 3.11 can also be tested in normal envs now.
I have removed the win-py37 run, which has started to fail on a Windows path error.
@astrofrog I just noticed you are already dropping support for 3.7 in #94 – should I sync with that?

There are strange failures with the development version of `glue-core`, throwing errors like
> ../../.tox/py39-test-devdeps/lib/python3.9/site-packages/glue/app/qt/feedback.py:10: in <module>
    from glue._deps import get_status_as_odict
../../.tox/py39-test-devdeps/lib/python3.9/site-packages/glue/_deps.py:227: in <module>
    ('plugins', plugins()),
../../.tox/py39-test-devdeps/lib/python3.9/site-packages/glue/_deps.py:217: in plugins
    package = entry_point.dist.name
E   AttributeError: 'EntryPoint' object has no attribute 'dist'

e.g. https://github.com/glue-viz/glue-wwt/actions/runs/4331625068/jobs/7563583949#step:9:156

all 3.8 and 3.9 platforms, although `glue`'s own tests are obviously still passing on 3.8.

**Comment by astrofrog** [comment]
@dhomeier - can you rebase/update this? Thanks!

**Comment by dhomeier** [comment]
@astrofrog, done. Should py312 be added now as well?

**Comment by astrofrog** [comment]
Yes please!

**Comment by dhomeier** [comment]
All passing!

**Review by astrofrog — APPROVED** [review]

**Pull request merged**
