### PR TITLE
Add publishing workflow to GH Actions

### PR DESCRIPTION
**Pull request by dhomeier**
## Description
Follow-up to #82 adding a publish_pure_python job.

### CODE REVIEW

**Comment by dhomeier** [comment]
I suppose there is no subset of tests working without a backend, since the core package cannot even be imported?
Shall I cut the tests until it is possible to set up a headless display in the publishing tests?

**Comment by astrofrog** [comment]
Yes can we just make the publish job be contingent on the main test matrix passing instead?

**Comment by dhomeier** [comment]
Oh; got the `test_command` working now (see comment in matrix).

Nonetheless having one job being contingent on another would in fact be useful (like for the minimal/extended test configurations), but I haven't found anything on how to do this so far.

**Review by astrofrog — APPROVED** [review]
Looks good thanks! I'll send a message later showing how to have dependent jobs

**Comment by astrofrog** [comment]
I'll merge this for now, we can do the dependent stuff later

**Pull request merged**
