### PR TITLE
Switch CI from Azure to GitHub actions

### PR DESCRIPTION
**Pull request by dhomeier**
## Description

Transition using the reusable workflows from https://github.com/OpenAstronomy/github-actions-workflows

### CODE REVIEW

**Comment by dhomeier** [comment]
Yes, just thought so as well – and the Windows jobs seemed to be stuck for 15 minutes after the actual tox runs again.

**Comment by dhomeier** [comment]
@astrofrog I don't know if there is a syntax to pull the dev branch of the workflows for testing if the `fail-fast` setting works as I believe it would, but that can certainly wait for a v1.0.3 release as well.

The Shapely 1.8.0 installations on macOS and Windows py310 seem to have similar `geos_c` problems – in fact the other Pythons are already on 1.8.1post1, so maybe that is the bugfix.

**Comment by astrofrog** [comment]
You can always replace @v1 by @main when calling the workflows to get the very latest version

**Comment by dhomeier** [comment]
OK, that would be better than accidentally staying stuck at **@v1.0.2** in any case.

**Comment by dhomeier** [comment]
So mac and win py310 have updated there Shapely as well.

**Comment by astrofrog** [comment]
Ok thanks! You can now revert back to using the default fast-fail as v1.0.3 of the workflows is out.

Also I think we can drop Python 3.6 as glue-core requires 3.7 (https://github.com/glue-viz/glue/blob/main/setup.cfg#L26) which might help resolve the remaining CI issues. Can you update this in setup.cfg too?

**Comment by dhomeier** [comment]
> Ok thanks! You can now revert back to using the default fast-fail as v1.0.3 of the workflows is out.

Already used in the last run (set in `tests` to `true` and in `allowed_failures` to `false`, though the py310 arguably could be moved back to the "required" tests now ;-).

**Comment by astrofrog** [comment]
I think we should just remove the fast-fail options from our config now - the default of 'false' is what we want I think

**Comment by dhomeier** [comment]
The default was `true` – at least for all envs in the same job; therefore I wanted this for the allowed failures.
`false` arguably would make debugging more tedious, but otoh avoid burning CI time if it's always the same env failing.

I think the middle path recommended for astropy coordinated packages was to define a smaller set of mandatory tests that first have to pass (actually not starting the full set before that, which seems not possible here, but at least anything failing early on on setup or so would cancel the remaining jobs soon).

**Review by astrofrog — APPROVED** [review]
Looks good! I agree about trying to follow something more like what we do in astropy with different stages of testing, though packages like this are low traffic enough that I'm not sure if it's worth the extra complexity. Fast failing is not a good option in any case as if you run the CI again you might not have the same job fail which makes debugging impossible.

**Pull request merged**
